apps:
    - name : reactFrame
      script : www/production.js
      exec_mode : fork
      instances : 1
      max_memory_restart : 800M
      autorestart : true
      node_args : [--es_staging]
      watch : [app, view, www]
      args : []
      env :
          webpack_on: true
          port : 8173
